### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jigsawye** [jigsawye/mostly-adequate-guide#1]
- [x] README.md
- [x] SUMMARY.md
- [x] ch1.md
- [x] ch2.md
- [x] ch3.md
- [x] ch4.md
- [x] ch5.md
- [x] ch6.md
- [ ] ch7.md
- [ ] ch8.md
- [ ] ch9.md
- [ ] ch10.md

**Comment by neighborhood999** [comment]
@jigsawye 我先認領 ch6 和 ch7。

**Comment by jigsawye** [comment]
@neighborhood999 👍 
除了原文外請參考對岸翻譯的版本，因為原文的英文實在太艱澀了。
一個翻不好可能跟原意相去甚遠，再麻煩了！
